FROM jicscicomp/scientific_python
MAINTAINER Matthew Hartley <Matthew.Hartley@jic.ac.uk>

RUN yum install -y epel-release

RUN yum install -y freeimage-devel

RUN pip install --no-binary :all: scikit-image
